version: '3'
services:
  api:
    image: "sovban/raspberry_2020:dotnetapi"
    restart: "always"
    container_name: "core_api_pi"
    ports:
      - "5000:5000"
    networks:
     - "api_bridge"
     
networks:
  api_bridge:
    driver: "bridge"